/**
 * Melvin Master Controller - Configuration and Constants
 * 
 * This header contains all the configuration constants and data structures
 * used by the Melvin master controller system.
 */

#ifndef MELVIN_CONFIG_H
#define MELVIN_CONFIG_H

#include <string>
#include <vector>

// Network configuration
#define WIFI_SSID "Melvin_Control_Network"
#define WIFI_PASS "MelvinController2025"
#define WIFI_CHANNEL 6
#define MAX_STA_CONN 10

// MQTT Broker configuration
#define MQTT_PORT 1883
#define MQTT_MAX_CLIENTS 10
#define MQTT_KEEPALIVE_SECONDS 60

// MQTT Topic Structure
#define MQTT_TOPIC_ROOT "melvin"
#define MQTT_TOPIC_EVENTS "melvin/events"
#define MQTT_TOPIC_CONTROLS "melvin/controls"
#define MQTT_TOPIC_DEVICES "melvin/devices"
#define MQTT_TOPIC_STATUS "melvin/status"

// Event notification settings
#define MQTT_QOS_EVENTS 0          // QoS level for event messages
#define MQTT_RETAIN_EVENTS false   // Don't retain event messages

// Control value constants
#define CONTROL_VALUE_OFF 0
#define CONTROL_VALUE_MAX 32768
#define CONTROL_VALUE_BOOLEAN_ON 1

// Flash pattern timing (milliseconds)
#define WIG_WAG_PERIOD_MS 1000
#define FLASH_PATTERN_PERIOD_MS 500

// Device heartbeat timeout (milliseconds)
#define HEARTBEAT_TIMEOUT_MS 30000

/**
 * Control Types - Different types of controls supported by the system
 */
enum ControlType {
    CONTROL_BOOLEAN = 0,    // Toggle switches, buttons (0 or 1)
    CONTROL_CONTINUOUS,     // Potentiometers, sliders (0-32768)
    CONTROL_ROTARY,         // Rotary encoders (0-32768 with wrap)
    CONTROL_JOYSTICK_2AXIS, // 2-axis joystick (two 0-32768 values)
    CONTROL_RGB_GROUP       // RGB group (three 0-32768 values)
};

/**
 * Device Types - Different categories of member controllers
 */
enum DeviceType {
    DEVICE_APRS_INTERFACE = 0,      // APRS radio interface
    DEVICE_CAMERA_INTERFACE,        // Camera control interface (pan/tilt, etc)
    DEVICE_DISPLAY,                 // Display devices (LCD, OLED, etc)
    DEVICE_EVENT_SENSOR_BANK,       // Event sensors send updates when state changes (door sensor, motion detector, etc)
    DEVICE_GPS_INTERFACE,           // GPS data module
    DEVICE_HID,                     // Human interface devices (switches, joysticks, etc)
    DEVICE_LOGGER,                  // Telemetry logger device (data logging and storage)
    DEVICE_ODBII_INTERFACE,         // ODBII vehicle data interface
    DEVICE_POLLED_SENSOR_BANK,      // Polled sensors are read on demand (themostat, barometer, etc)
    DEVICE_RELAY_BANK,              // Relay control for high-current devices (lights, motors, etc)
    DEVICE_SPOTLIGHT_INTERFACE      // Spotlight control interface (pan/tilt)
};

/**
 * Event Types - Different types of events that can be generated by controllers
 *  - Each event type corresponds to a specific state change or action
 *  - These events can be used to trigger actions or notifications within the system
 *  - Examples include gear changes, light activations, door states, etc.
 *  - Not all event type triggers are implemented in the current system
 *     but are defined here for future expansion and compatibility.
 */
enum EventType {
    EVENT_GEAR_PARK = 0,        // Vehicle in park gear
    EVENT_GEAR_REVERSE,         // Vehicle in reverse gear
    EVENT_GEAR_NEUTRAL,         // Vehicle in neutral gear
    EVENT_GEAR_DRIVE,           // Vehicle in drive gear
    EVENT_HIGH_BEAM_ON,         // High beam headlights turned on
    EVENT_HIGH_BEAM_OFF,        // High beam headlights turned off
    EVENT_LOW_BEAM_ON,          // Low beam headlights turned on
    EVENT_LOW_BEAM_OFF,         // Low beam headlights turned off
    EVENT_TURN_SIGNAL_LEFT_ON,  // Left turn signal activated
    EVENT_TURN_SIGNAL_LEFT_OFF, // Left turn signal deactivated
    EVENT_TURN_SIGNAL_RIGHT_ON, // Right turn signal activated
    EVENT_TURN_SIGNAL_RIGHT_OFF,// Right turn signal deactivated
    EVENT_HAZARD_ON,            // Hazard lights activated
    EVENT_HAZARD_OFF,           // Hazard lights deactivated
    EVENT_BRAKE_ON,             // Brake pedal pressed
    EVENT_BRAKE_OFF,            // Brake pedal released
    EVENT_DOOR_OPEN,            // Door opened
    EVENT_DOOR_CLOSED,          // Door closed
    EVENT_IGNITION_ON,          // Ignition turned on
    EVENT_IGNITION_OFF,         // Ignition turned off
    EVENT_ENGINE_START,         // Engine started
    EVENT_ENGINE_STOP,          // Engine stopped
    EVENT_MOTION_DETECTED,      // Motion sensor triggered
    EVENT_MOTION_CLEARED,       // Motion sensor cleared
    EVENT_BUTTON_PRESSED,       // Generic button press event
    EVENT_BUTTON_RELEASED       // Generic button release event
};

/**
 * Flash Pattern Types - Different flashing patterns for lighting
 */
enum FlashPattern {
    FLASH_ALTERNATING = 0, // Alternating flash pattern (flash each side in sequence)
    FLASH_ALTERNATING_II,  // Double Alternating flash pattern (flash twice each side in sequence)
    FLASH_ALTERNATING_III, // Triple Alternating flash pattern (flash three times each side in sequence)
    FLASH_WIG_WAG,         // Wig-wag flash pattern (one side on, then the other)
    FLASH_STROBE,          // Strobe flash pattern (all on/off rapidly)
    FLASH_SKIPPER,         // Strobe that skips every other flash
    FLASH_NONE             // No flashing. All on or off.
};

/**
 * Control Structure - Represents a single control endpoint
 */
struct Control {
    uint16_t base_address;      // Base address for this control
    uint16_t control_number;    // Control number within the base address
    ControlType type;           // Type of control
    uint16_t current_value;     // Current control value (0-32768)
    uint16_t current_value_y;   // Second axis for joystick controls
    uint16_t current_value_z;   // Third value for RGB controls
    std::string name;           // Human-friendly name
    bool is_group;              // True if this is a group control
    std::vector<uint16_t> group_members; // Member control IDs if this is a group
    FlashPattern flash_pattern; // Flash pattern for this control
    uint32_t last_flash_time;   // Last flash state change time
    bool flash_state;           // Current flash state (on/off)
    
    Control() : base_address(0), control_number(0), type(CONTROL_BOOLEAN), 
                current_value(0), current_value_y(0), current_value_z(0),
                is_group(false), flash_pattern(FLASH_NONE), 
                last_flash_time(0), flash_state(false) {}
};

/**
 * Device Structure - Represents a member controller device
 */
struct Device {
    std::string device_id;          // Unique device identifier
    std::string ip_address;         // IP address of the device
    DeviceType device_type;         // Type of device
    std::string name;               // Human-friendly name
    uint32_t last_heartbeat;        // Last communication timestamp
    bool is_online;                 // Device online status
    std::vector<uint16_t> controls; // List of control IDs this device manages
    
    Device() : device_type(DEVICE_APRS_INTERFACE), last_heartbeat(0), is_online(false) {}
};

/**
 * MQTT Event Structure - Represents an event published to MQTT
 */
struct MQTTEvent {
    std::string device_id;          // Device that generated the event
    std::string control_name;       // Name of the control that changed
    uint16_t control_id;            // ID of the control
    uint16_t old_value;             // Previous control value
    uint16_t new_value;             // New control value
    uint32_t timestamp;             // Event timestamp (millis())
    EventType event_type;           // Type of event (if applicable)
    
    MQTTEvent() : control_id(0), old_value(0), new_value(0), timestamp(0), event_type(EVENT_BUTTON_PRESSED) {}
};

/**
 * MQTT Control Command Structure - Commands sent via MQTT to control devices
 */
struct MQTTControlCommand {
    std::string target_device_id;   // Device to receive the command
    std::string control_name;       // Control to modify
    uint16_t control_id;            // Control ID
    uint16_t value;                 // New control value
    uint16_t value_y;               // Second axis (for joystick/RGB)
    uint16_t value_z;               // Third value (for RGB)
    bool immediate;                 // Process immediately vs. queued
    
    MQTTControlCommand() : control_id(0), value(0), value_y(0), value_z(0), immediate(true) {}
};



#endif // MELVIN_CONFIG_H